site_name: autoclass
# site_description: 'A short description of my project'
repo_url: https://github.com/smarie/python-autoclass
pages:
    - Home: index.md
    - Usage details: usage.md
    - Validators list: validators.md
    - Changelog: changelog.md
theme: material  # readthedocs  mkdocs

markdown_extensions:
  - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite(guess_lang=false)
  - toc(permalink=true)